# Generated by Django 5.2.12 on 2026-03-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aldryn_forms", "0026_fileuploadfieldplugin_is_private_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="widget_value",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Value"
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="value",
            field=models.CharField(max_length=255, verbose_name="Label"),
        ),
    ]
