# Generated by Django 5.2.15 on 2026-06-17 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aldryn_forms", "0027_option_widget_value_alter_option_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=255, verbose_name="Name"),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
        migrations.AddField(
            model_name="formplugin",
            name="validation",
            field=models.CharField(
                default="", max_length=255, verbose_name="Form validation"
            ),
        ),
    ]
