# Generated by Django 6.0.6 on 2026-07-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aldryn_forms", "0027_option_widget_value_alter_option_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="formplugin",
            name="hide_form_after_redirection",
            field=models.BooleanField(
                default=False, verbose_name="Hide the form after redirection."
            ),
        ),
        migrations.AddField(
            model_name="formplugin",
            name="message_on_form",
            field=models.BooleanField(
                default=False, verbose_name="Show the message on the form."
            ),
        ),
    ]
