# Generated by Django 6.0.7 on 2026-07-24 11:03

import aldryn_forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_forms', '0028_formplugin_hide_form_after_redirection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datefieldplugin',
            name='pattern',
            field=models.CharField(blank=True, help_text="The pattern attribute specifies a regular expression the form control's value should match.", max_length=255, null=True, validators=[aldryn_forms.models.validate_pattern], verbose_name='Pattern'),
        ),
        migrations.AddField(
            model_name='datetimelocalfieldplugin',
            name='pattern',
            field=models.CharField(blank=True, help_text="The pattern attribute specifies a regular expression the form control's value should match.", max_length=255, null=True, validators=[aldryn_forms.models.validate_pattern], verbose_name='Pattern'),
        ),
        migrations.AddField(
            model_name='emailfieldplugin',
            name='pattern',
            field=models.CharField(blank=True, help_text="The pattern attribute specifies a regular expression the form control's value should match.", max_length=255, null=True, validators=[aldryn_forms.models.validate_pattern], verbose_name='Pattern'),
        ),
        migrations.AddField(
            model_name='fieldplugin',
            name='pattern',
            field=models.CharField(blank=True, help_text="The pattern attribute specifies a regular expression the form control's value should match.", max_length=255, null=True, validators=[aldryn_forms.models.validate_pattern], verbose_name='Pattern'),
        ),
        migrations.AddField(
            model_name='fileuploadfieldplugin',
            name='pattern',
            field=models.CharField(blank=True, help_text="The pattern attribute specifies a regular expression the form control's value should match.", max_length=255, null=True, validators=[aldryn_forms.models.validate_pattern], verbose_name='Pattern'),
        ),
        migrations.AddField(
            model_name='imageuploadfieldplugin',
            name='pattern',
            field=models.CharField(blank=True, help_text="The pattern attribute specifies a regular expression the form control's value should match.", max_length=255, null=True, validators=[aldryn_forms.models.validate_pattern], verbose_name='Pattern'),
        ),
        migrations.AddField(
            model_name='multiplefilesuploadfieldplugin',
            name='pattern',
            field=models.CharField(blank=True, help_text="The pattern attribute specifies a regular expression the form control's value should match.", max_length=255, null=True, validators=[aldryn_forms.models.validate_pattern], verbose_name='Pattern'),
        ),
        migrations.AddField(
            model_name='textareafieldplugin',
            name='pattern',
            field=models.CharField(blank=True, help_text="The pattern attribute specifies a regular expression the form control's value should match.", max_length=255, null=True, validators=[aldryn_forms.models.validate_pattern], verbose_name='Pattern'),
        ),
        migrations.AddField(
            model_name='timefieldplugin',
            name='pattern',
            field=models.CharField(blank=True, help_text="The pattern attribute specifies a regular expression the form control's value should match.", max_length=255, null=True, validators=[aldryn_forms.models.validate_pattern], verbose_name='Pattern'),
        ),
    ]
