# Generated by Django 6.0.6 on 2026-07-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aldryn_forms", "0028_formplugin_hide_form_after_redirection_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Validation rules"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="formplugin",
            name="validation_rules",
            field=models.ManyToManyField(blank=True, to="aldryn_forms.validationrule"),
        ),
    ]
