# Generated by Django 6.0.7 on 2026-07-27 08:08

import aldryn_forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aldryn_forms", "0028_formplugin_hide_form_after_redirection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailfieldplugin",
            name="pattern",
            field=models.CharField(
                blank=True,
                help_text="A regular expression to match for the value. It must be a valid JavaScript regular expression.",
                max_length=255,
                null=True,
                validators=[aldryn_forms.models.validate_pattern],
                verbose_name="Pattern",
            ),
        ),
        migrations.AddField(
            model_name="fieldplugin",
            name="pattern",
            field=models.CharField(
                blank=True,
                help_text="A regular expression to match for the value. It must be a valid JavaScript regular expression.",
                max_length=255,
                null=True,
                validators=[aldryn_forms.models.validate_pattern],
                verbose_name="Pattern",
            ),
        ),
        migrations.AlterField(
            model_name="urlfieldplugin",
            name="pattern",
            field=models.CharField(
                blank=True,
                help_text="A regular expression to match for the value. It must be a valid JavaScript regular expression.",
                max_length=255,
                null=True,
                validators=[aldryn_forms.models.validate_pattern],
                verbose_name="Pattern",
            ),
        ),
    ]
