# Generated by Django 6.0.6 on 2026-07-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aldryn_forms", "0029_validationrule_formplugin_validation_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="datefieldplugin",
            name="pattern",
            field=models.CharField(
                blank=True,
                help_text="The pattern attribute specifies a regular expression the form control's value should match.",
                max_length=255,
                verbose_name="Pattern",
            ),
        ),
        migrations.AddField(
            model_name="datetimelocalfieldplugin",
            name="pattern",
            field=models.CharField(
                blank=True,
                help_text="The pattern attribute specifies a regular expression the form control's value should match.",
                max_length=255,
                verbose_name="Pattern",
            ),
        ),
        migrations.AddField(
            model_name="emailfieldplugin",
            name="pattern",
            field=models.CharField(
                blank=True,
                help_text="The pattern attribute specifies a regular expression the form control's value should match.",
                max_length=255,
                verbose_name="Pattern",
            ),
        ),
        migrations.AddField(
            model_name="fieldplugin",
            name="pattern",
            field=models.CharField(
                blank=True,
                help_text="The pattern attribute specifies a regular expression the form control's value should match.",
                max_length=255,
                verbose_name="Pattern",
            ),
        ),
        migrations.AddField(
            model_name="fileuploadfieldplugin",
            name="pattern",
            field=models.CharField(
                blank=True,
                help_text="The pattern attribute specifies a regular expression the form control's value should match.",
                max_length=255,
                verbose_name="Pattern",
            ),
        ),
        migrations.AddField(
            model_name="imageuploadfieldplugin",
            name="pattern",
            field=models.CharField(
                blank=True,
                help_text="The pattern attribute specifies a regular expression the form control's value should match.",
                max_length=255,
                verbose_name="Pattern",
            ),
        ),
        migrations.AddField(
            model_name="multiplefilesuploadfieldplugin",
            name="pattern",
            field=models.CharField(
                blank=True,
                help_text="The pattern attribute specifies a regular expression the form control's value should match.",
                max_length=255,
                verbose_name="Pattern",
            ),
        ),
        migrations.AddField(
            model_name="textareafieldplugin",
            name="pattern",
            field=models.CharField(
                blank=True,
                help_text="The pattern attribute specifies a regular expression the form control's value should match.",
                max_length=255,
                verbose_name="Pattern",
            ),
        ),
        migrations.AddField(
            model_name="timefieldplugin",
            name="pattern",
            field=models.CharField(
                blank=True,
                help_text="The pattern attribute specifies a regular expression the form control's value should match.",
                max_length=255,
                verbose_name="Pattern",
            ),
        ),
    ]
